name: Fetch Famous Artwork Daily

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Haha
      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 \
            libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 \
            libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 \
            libpango-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 \
            libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 \
            libxtst6 ca-certificates fonts-liberation libappindicator1 \
            libnss3 lsb-release xdg-utils wget
      # Checkout the repository
      - uses: actions/checkout@v2

      # Install Bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest' # Specify the Bun version or use 'latest'

      # Install dependencies and run the script
      - name: Install dependencies and run script
        run: |
          bun install
          bun start

      - name: Commit files
        run: |
          # Hard-code user configuration
          git reset --hard
          git config --global user.name "keohanoi"
          git config --global user.email "nguyentruongkhang22@gmail.com"
          git remote set-url origin https://keohanoi:${{ secrets.SuperSecret }}@github.com/keohanoi/keohanoi.git
          git pull
          # Checkout the branch so we can push back to it
          git checkout main
          git add -A
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m ":rocket: Fetch GitHub Daily Artwork at $(date +'%Y-%m-%d %H:%M')")
          git push
