name: Fetch Famous Artwork Daily

on:
  schedule:
    - cron: '0 0,8,16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Install Bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest' # Specify the Bun version or use 'latest'

      # Install dependencies and run the script
      - name: Install dependencies and run script
        run: |
          bun install
          bun start

      - name: Commit files
        run: |
          # Configure git user
          git config --global user.name "keohanoi"
          git config --global user.email "nguyentruongkhang22@gmail.com"
          git remote set-url origin https://keohanoi:${{ secrets.SuperSecret }}@github.com/keohanoi/keohanoi.git
          
          # Check for changes and commit if any exist
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m ":rocket: Fetch GitHub Daily Artwork at $(date +'%Y-%m-%d %H:%M')"
            git push
          else
            echo "No changes to commit"
          fi
