name: Fetch Famous Artwork Daily

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies and run script
        run: |
          # Run script
          npm ci
          npm run crawl --if-present

      - name: Commit files
        run: |
          # Hard-code user configuration
          git config --global user.name "keohanoi"
          git config --global user.email "nguyentruongkhang22@gmail.com"
          git remote set-url origin https://keohanoi:${{ secrets.SuperSecret }}@github.com/keohanoi/keohanoi.git
          git pull
          # Checkout the branch so we can push back to it
          git checkout main
          git add -A
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m ":rocket: Fetch GitHub Daily Artwork at $(date +'%Y-%m-%d %H:%M')")
          git push
